// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-feed-tickets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-feed-tickets.ts
var list_feed_tickets_default = defineTool({
  name: "list_feed_tickets",
  title: "Listar entradas a la venta",
  description: "Lista las entradas de concierto a la venta visibles en la red de confianza del usuario (amigos y amigos de amigos). Permite filtrar por artista o ciudad.",
  inputSchema: {
    artist: z.string().trim().min(1).optional().describe("Filtro parcial por nombre de artista."),
    city: z.string().trim().min(1).optional().describe("Filtro parcial por ciudad."),
    limit: z.number().int().min(1).max(50).default(20).optional().describe("N\xFAmero m\xE1ximo de entradas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ artist, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tickets").select("id, artist, venue, city, event_date, price, quantity, ticket_type, status, description").gte("event_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)).order("event_date", { ascending: true }).limit(limit ?? 20);
    if (artist) query = query.ilike("artist", `%${artist}%`);
    if (city) query = query.ilike("city", `%${city}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-wanted-tickets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_wanted_tickets_default = defineTool2({
  name: "list_wanted_tickets",
  title: "Listar entradas buscadas",
  description: "Lista las entradas que la red de confianza del usuario est\xE1 buscando. \xDAtil para saber a qui\xE9n le puedes ofrecer una entrada.",
  inputSchema: {
    artist: z2.string().trim().min(1).optional().describe("Filtro parcial por nombre de artista."),
    city: z2.string().trim().min(1).optional().describe("Filtro parcial por ciudad."),
    limit: z2.number().int().min(1).max(50).default(20).optional().describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ artist, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("wanted_tickets").select("id, artist, city, event_date, quantity, created_at").gte("event_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)).order("event_date", { ascending: true }).limit(limit ?? 20);
    if (artist) query = query.ilike("artist", `%${artist}%`);
    if (city) query = query.ilike("city", `%${city}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { wanted_tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-tickets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_tickets_default = defineTool3({
  name: "list_my_tickets",
  title: "Listar mis entradas",
  description: "Lista las entradas publicadas por el propio usuario, incluyendo su estado (available o sold), y tambi\xE9n sus b\xFAsquedas activas.",
  inputSchema: {
    status: z3.enum(["available", "sold", "all"]).default("all").optional().describe("Filtrar por estado de la entrada.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    let ticketQuery = supabase.from("tickets").select("id, artist, venue, city, event_date, price, quantity, ticket_type, status, description").eq("user_id", userId).order("event_date", { ascending: true });
    if (status && status !== "all") ticketQuery = ticketQuery.eq("status", status);
    const [tickets, wanted] = await Promise.all([
      ticketQuery,
      supabase.from("wanted_tickets").select("id, artist, city, event_date").eq("user_id", userId).order("event_date", { ascending: true })
    ]);
    const error = tickets.error ?? wanted.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { tickets: tickets.data ?? [], wanted_tickets: wanted.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-ticket.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_ticket_default = defineTool4({
  name: "create_ticket",
  title: "Publicar entrada a la venta",
  description: "Publica una entrada de concierto a la venta en la red de confianza del usuario. El precio debe respetar el precio original (Trusticket no permite especulaci\xF3n).",
  inputSchema: {
    artist: z4.string().trim().min(1).max(100).describe("Nombre del artista o grupo."),
    venue: z4.string().trim().min(1).max(150).describe("Sala o recinto del concierto."),
    city: z4.string().trim().min(1).max(100).describe("Ciudad del concierto."),
    event_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha del evento en formato YYYY-MM-DD."),
    price: z4.number().nonnegative().describe("Precio por entrada en euros."),
    quantity: z4.number().int().min(1).max(20).default(1).optional().describe("N\xFAmero de entradas disponibles."),
    ticket_type: z4.string().trim().min(1).max(60).describe("Tipo de entrada (p. ej. General, Pista, Grada)."),
    description: z4.string().trim().max(100).optional().describe("Nota opcional, m\xE1ximo 100 caracteres.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tickets").insert({
      user_id: ctx.getUserId(),
      artist: input.artist,
      venue: input.venue,
      city: input.city,
      event_date: input.event_date,
      price: input.price,
      quantity: input.quantity ?? 1,
      ticket_type: input.ticket_type,
      description: input.description ?? null,
      status: "available"
    }).select("id, artist, venue, city, event_date, price, quantity, ticket_type, status").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Entrada publicada: ${JSON.stringify(data)}` }],
      structuredContent: { ticket: data }
    };
  }
});

// src/lib/mcp/tools/create-wanted-ticket.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_wanted_ticket_default = defineTool5({
  name: "create_wanted_ticket",
  title: "Publicar b\xFAsqueda de entrada",
  description: "Publica una b\xFAsqueda de entrada para que la red de confianza del usuario sepa qu\xE9 concierto est\xE1 buscando.",
  inputSchema: {
    artist: z5.string().trim().min(1).max(100).describe("Nombre del artista o grupo que busca."),
    city: z5.string().trim().min(1).max(100).describe("Ciudad del concierto."),
    quantity: z5.number().int().min(1).max(99).default(1).optional().describe("N\xFAmero de entradas que busca."),
    event_date: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha del evento en formato YYYY-MM-DD."),
    email_notifications: z5.boolean().default(true).optional().describe("Recibir email cuando aparezca una entrada que coincida.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("wanted_tickets").insert({
      user_id: ctx.getUserId(),
      artist: input.artist,
      city: input.city,
      quantity: input.quantity ?? 1,
      event_date: input.event_date,
      email_notifications: input.email_notifications ?? true
    }).select("id, artist, city, event_date, quantity, email_notifications").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `B\xFAsqueda publicada: ${JSON.stringify(data)}` }],
      structuredContent: { wanted_ticket: data }
    };
  }
});

// src/lib/mcp/tools/update-ticket-status.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var update_ticket_status_default = defineTool6({
  name: "update_ticket_status",
  title: "Marcar entrada como vendida o disponible",
  description: "Cambia el estado de una entrada propia entre 'available' (en venta) y 'sold' (vendida). Solo afecta a entradas del propio usuario.",
  inputSchema: {
    ticket_id: z6.string().uuid().describe("ID de la entrada a actualizar."),
    status: z6.enum(["available", "sold"]).describe("Nuevo estado de la entrada.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tickets").update({ status }).eq("id", ticket_id).eq("user_id", ctx.getUserId()).select("id, artist, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No se encontr\xF3 una entrada propia con ese ID." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `Estado actualizado: ${JSON.stringify(data)}` }],
      structuredContent: { ticket: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ystnsszlaqhwysgptysd";
var mcp_default = defineMcp({
  name: "trusticket",
  title: "Trusticket",
  version: "0.1.0",
  instructions: "Herramientas de Trusticket, la red de confianza para comprar y vender entradas de conciertos entre amigos. Usa `list_feed_tickets` para ver entradas a la venta en la red del usuario, `list_wanted_tickets` para ver qu\xE9 busca su red, `list_my_tickets` para sus propias entradas y b\xFAsquedas, `create_ticket` y `create_wanted_ticket` para publicar, y `update_ticket_status` para marcar una entrada como vendida o volver a ponerla en venta. El contacto entre usuarios es siempre por email dentro de la aplicaci\xF3n; no existe mensajer\xEDa interna.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_feed_tickets_default,
    list_wanted_tickets_default,
    list_my_tickets_default,
    create_ticket_default,
    create_wanted_ticket_default,
    update_ticket_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
